name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: buildozer-global-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        command: buildozer android debug
        repository_root: .

    - name: Upload APK Artifact
      uses: actions/artifacts@v4
      with:
        name: Attendance-App-Debug
        path: bin/*.apk
