name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Build APK with Official Buildozer Action
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        # বিল্ড শুরুর আগে Cython ও অন্যান্য টুলস প্রিপেয়ার করার জন্য কমান্ড কম্বিনেশন
        command: pip3 install --user --upgrade Cython==0.29.36 virtualenv setuptools; buildozer android debug
        buildozer_version: master

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Android-APK
        path: bin/*.apk
